### ISSUE TITLE
What about the UDAF ?

### ISSUE THREAD

**Issue by ChenZhongPu** [spirom/LearningSpark#2]
I would like to implement **UDAF** (user-define aggregation function) like `sum` in `SparkSQL`, and how to do it ?

**Comment by spirom** [comment]
It turns out this is being tracked in [SPARK-3947](https://issues.apache.org/jira/browse/SPARK-3947) -- doesn't seem to be coming to Spark SQL any time soon. In the meantime I'm trying to figure out how they work in Hive. I just added a Hive UDF example today and it was very simple, but UDAF's are more complex.

**Comment by spirom** [comment]
See `src/main/scala/hiveql/SimpleUDAF.scala` and `src/main/java/hiveql/SumLargeSalesUDAF.java` for an example that "works" in HiveQL. However, see [this thread on the developer list](http://apache-spark-developers-list.1001551.n3.nabble.com/In-Spark-SQL-is-there-support-for-distributed-execution-of-native-Hive-UDAFs-tc11753.html) and [SPARK-4233](https://issues.apache.org/jira/browse/SPARK-4233) to understand that in Spark 1.3.1 UDAF execution is not currently distributed (because there's no support for partial aggregation), although it seems it soon will be.

**Comment by eliasah** [comment]
The issue concerning UDAF support on Spark SQL seems to be resolved now with [SPARK-39487](https://issues.apache.org/jira/browse/SPARK-3947) in Spark 1.5.0

**Comment by spirom** [comment]
I've added some simple examples of this experimental feature in `dataframe/UDAF.scala` and `sql/UDAF.scala`. I'm going to close this issue for now although I think there's more of it to be explored.
